### ISSUE TITLE
Is it OK if I submit beancount.el to MELPA?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount-mode#4] opened 2020-10-13 06:26 UTC
I use `beancount.el` regularly and I manage most of my emacs configuration using use-package, which is designed to support fetching packages from official sources like ELPA and MELPA. I thought it might be fun to try to submit beancount to MELPA. I have a Per https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org, I should "please notify the authors prior to submitting and include them in the pull request process".

I'm not exactly what the process is going to be like. It seems like the MELPA maintainers do a code review, not only on the "recipe", but on the elisp code of the package in question. I can try to turn any feedback into PRs on beancount.el although I understand you may not be interested in merging it just to please the maintainers of some other project.

I have a branch at https://github.com/glasserc/melpa/tree/add-beancount which seems to work, so if you're OK with it, I'll open a PR on the main MELPA repository!

-- Ethan Glasser-Camp

**Comment by bhipple** [comment] 2021-05-09 17:20
The melpa review/overhead is extremely lightweight and mostly automated, so it shouldn't be a maintenance burden.  It'd be really great to have this package there so it can be easily fetched via `use-package` and added to tools like the `spacemacs` finance layer someday.

**Comment by dnicolodi** [comment] 2021-05-09 18:21
This issue is missing most of the context (we had some troubles with existing issues when we split the ropo out from the main beancount repo). The main issue is that I don't want to commit to backward compatibility for the code in its current form. I know that MELPA does has few promises about backward compatibility, but it would be rude to break the workflow of susers. I think that as long as the package is only available via git it is understood that it is somehow experimental.

**Comment by hxegon** [comment] 2022-01-30 20:29
Don't know anything about melpa packaging but would also find this useful. If the issue is making expectations about workflow instability clear, do you think initially releasing it as `beancount-experimental` (or something similar) would be sufficient?

**Comment by dnicolodi** [comment] 2022-01-31 12:42
What would be the advantages of having `beancount.el` on MELPA other than a slightly easier installation?

**Comment by gsingh93** [comment] 2022-04-08 00:14
It makes the installation easier, and can be used with `use-package` which is nice. Would you consider supporting https://github.com/quelpa/quelpa#by-recipe instead?

**Comment by dnicolodi** [comment] 2022-04-08 00:53
I may be missing something but there is nothing to do from the bencount-mode side to support quelpa.

**Comment by gsingh93** [comment] 2022-04-08 01:09
You're right, my mistake. I'll go ahead and use quelpa for now until this is on MELPA (if ever).

**Comment by lionel-** [comment] 2022-12-31 07:15
> I know that MELPA does has few promises about backward compatibility, but it would be rude to break the workflow of susers. I think that as long as the package is only available via git it is understood that it is somehow experimental.

The README in the repo does not mention that beancount-mode is experimental though, so I would not have made that inference. I think a clear disclaimer in the README and perhaps in the docstring of `beancount-mode` would clear that up for both git users and MELPA users.

**Comment by monnier** [comment] 2024-04-29 21:23
FWIW, I just added Beancount to NonGNU ELPA.  Given its `Version:0` in the header, it will not actually be released into NonGNU ELPA for now, but only in NonGNU-devel ELPA.

But AFAICT, the code has been fairly stable for the last several years, so maybe it deserves to have an actual release.

**Comment by dnicolodi** [comment] 2024-04-29 21:30
Thanks @monnier. I would still like to find some time and clean some things up. I'm also collecting local tweaks that would be nice to fold back into `beancount.el` proper... I even started to work on a `beancount-mode` based on tree-sitter, but I didn't manage to finish it. I got lost trying to do indentation with tree-sitter. It does not seem obvious for languages that use semantic indentation.

**Comment by monnier** [comment] 2024-04-29 21:42
> Thanks @monnier. I would still like to find some time and clean some things
> up. I'm also collecting local tweaks that would be nice to fold back into
> `beancount.el` proper... I even started to work on a `beancount-mode` based
> on tree-sitter, but I didn't manage to finish it. I got lost trying to do
> indentation with tree-sitter. It does not seem obvious for languages that
> use semantic indentation.

It's good that there's more to do.  But in the mean time, you do have
real users who have to go through hoops to use your mode simply because
it hasn't been labeled as "a release" even though it's not less stable
than most other packages out there.

Don't wait until the mode is dead before making a release.

**Comment by zilti** [comment] 2024-06-23 12:27
Emacs 30 will add repository cloning support to `use-package` similar to tools like elpaca, it's available for older versions as "vc-use-package". 
For reference, this is my code to add beancount-mode to my setup:

```emacs-lisp
(use-package beancount
  :vc (:fetcher github :repo "beancount/beancount-mode"))
```

The package name has to be "beancount", not "beancount-mode", because the main code is in the "beancount" module in beancount.el.

**Comment by monnier** [comment] 2024-06-23 15:29
Sorry, maybe I'm just confused, but: how is this related to the subject "Is it OK if I submit beancount.el to MELPA"?
[ BTW, maybe we should close this issue?  I haven't checked if it's actually been added to MELPA, but if it hasn't yet, there's not much need to add it now that it's in NonGNU.  ]

**Comment by monnier** [comment] 2024-06-23 16:22
Oh, I think I get it: you're pointing out another alternative way to install the package (just like I did when I announced that I had added it to NonGNU).  Sorry 'bout the noise.

**Comment by blais** [comment] 2024-06-24 02:58
I have zero understanding of packaging in Emacs (and wish to know the very least amount about it) but adding the mode to one of the repos makes sense to me.

```
Don't wait until the mode is dead before making a release.
```
What do I need to do to make a release? In other words, define "making a release" for Emacs modes?
I thought those were largely tagged by date (AFAICT from package-list-packages).

**Comment by monnier** [comment] 2024-06-24 03:21
> I have zero understanding of packaging in Emacs (and wish to know the very
> least amount about it) but adding the mode to one of the repos makes sense
> to me.

It's already in NonGNU ELPA, which is included by default in
`package-archives`, so if you want to do the least amount of work,
there's nothing left to do 🙂

> ```
> Don't wait until the mode is dead before making a release.
> ```
> What do I need to do to make a release?

Bump up the

    ;; Version: 0

in `beancount.el`.

> In other words, define "making a release" for Emacs modes?
> I thought those were largely tagged by date (AFAICT from package-list-packages).

You're probably seeing MELPA version numbers.  All other archives (or at
least the ones with which I'm familiar: GNU ELPA, MELPA-Stable,
NonGNU-ELPA, GNU-devel ELPA, NonGNU-devel ELPA) use version numbers
derived from the version number chosen by the package's maintainer.

[ And yes, the MELPA exception makes for fun failure modes when
  a package requires package foo-5.7 and the package manager thinks that
  the ancient foo-20100713 is more than good enough for that.  ]

**Comment by blais** [comment] 2024-06-24 03:29
0.9.0 released!  I also added a tag.

**Closed as completed by blais** 2024-06-24 03:29 UTC

**Comment by monnier** [comment] 2024-06-24 12:36
> 0.9.0 released!  I also added a tag.

Looks like it worked:
https://lists.gnu.org/archive/html/gnu-emacs-sources/2024-06/msg00059.html
http://elpa.nongnu.org/nongnu/beancount.html

Yay!  Juste à temps pour la St-Jean!
